# Generated by Django 5.0.2 on 2024-02-19 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_employee_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='work_date',
            field=models.DateField(),
        ),
    ]
