# Generated by Django 5.0.2 on 2024-02-19 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_alter_attendance_work_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
